config/routes.rb
Rails.application.routes.draw do

  devise_for :users,  controllers: { sessions: 'users/sessions'},
                      path_names: { sign_in: 'login', sign_up: 'signup'}
                 
  get 'home' => 'home#index'

  root 'home#index'

  resources :stories do
    post 'add_continuation', on: :member
  end

  resources :users

  get 'about' => 'home#about'

end

app/models/story.rb
class Story < ActiveRecord::Base
  belongs_to :users
  belongs_to :parent, class_name: 'Story'
  has_many :children, class_name: 'Story', foreign_key: 'parent_id'

  validates :title, presence: true, if: :root?
  validates :text, presence: true

  scope :root, -> { where parent: nil }

  def root?
  	parent.nil?
  end

  def last_created
  	order(created_at: :desc)
  end

  def parents
  	return [] unless self.parent
  	[self.parent] | self.parent.parents
   end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :stories
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  	def configure_permitted_parameters
  		devise_parameter_sanitizer.for(:sign_up) << :name
  	end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	def index
	end
	def about
	end
end

app/controllers/stories_controller.rb
class StoriesController < ApplicationController
  def index
    @stories = Story.root
  end

  def show
  	@story = Story.find(params[:id])
  end

  def new
  	@story = Story.new
  end

  def edit
    @story = Story.find(params[:id])
  end

  def add_continuation
    @parent = Story.find(params[:id])
    @story = @parent.children.build story_params

    if @story.save
      flash[:notice] = "Has creado tu historia correctamente"
      redirect_to @story
    else
      flash[:error] = "No se ha podido crear tu historia. Revisa los campos"
      redirect_to @parent
    end 
  end

  def create
  	@story = Story.new story_params

  	if @story.save
			flash[:notice] = "Has creado tu historia correctamente"
			redirect_to @story
		else
			flash[:error] = "No se ha podido crear tu historia. Revisa los campos"
			render 'new'
		end	
  end

  def update
    @story = Story.find(params[:id])
    if @story.update(story_params)
      redirect_to @story
    else
      render :edit
    end
  end

  def delete
    @story = Story.destroy(params[:id])
  end

protected
  def story_params
  	params.require(:story).permit(:title, :text)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
# before_filter :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # You can put the params you want to permit in the empty array.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.for(:sign_in) << :attribute
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: :show

	def index
	end

	def show
		@user = User.find(params[:id])
		render 'users/show'
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stories_helper.rb
module StoriesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/about.html.erb
<body class="background">

<nav class="nav">
	<ul>
		<li class="elemnav1">
			<h2>Snippets.</h2>
		</li>
		<% if user_signed_in? %>

			<li class="elemnav2 buttonsession">
				<%= link_to "About Snippets", about_path, :class => "button" %>
				<%= link_to "#{current_user.name}'s pad", user_path(current_user.id), :class => "button" %>
				<%= link_to "Sign out", destroy_user_session_path, :class => "button", method: :delete %>
			</li>
		<% else %>
		
			<li class="elemnav2 buttonsession">
				<%= link_to "About Snippets", about_path %>
				<%= link_to "Sign in", new_user_session_path, :class => "button" %>
				<%= link_to "Sign up", new_user_registration_path, :class => "button" %>
			</li>
		
		<% end %>

			
	</ul>	

</nav>

	<div class="about">
		<h2>¿Qué es Snippets?</h2>

		<p>Snippets es un lugar donde puedes dejar volar tu imaginación y crear cualquier historia que te venga a la mente, y después compartirla con otros escritores que podrán continuar tu historia o simplemente disfrutar de su lectura.</p>
		<p>Al igual que los demás pueden crear nuevos hilos de tu historia, tú también podrás continuar historias de otros usuarios y colaborar así en un sinfín de posibles hilos argumentales.</p>

		<%= link_to "Go to Stories >>", stories_path, :class => "buttonsession" %>

	</div>
</body>

app/views/home/index.html.erb
<body class="backgroundhome">
	<header>
		<div class="socialmedia">
			<a href="http://www.twitter.com/beaguju"><%= image_tag "twitterb.png", :class => "icon" %></a>
			<a href="https://www.facebook.com/GuJuLi"><%= image_tag "facebookb.png", :class => "icon" %></a>
			<a href="http://es.linkedin.com/pub/beatriz-gujuli-murillo/19/615/974/"><%= image_tag "linkedinb.png", :class => "icon" %></a>
			<a href="https://www.google.com/+BeatrizGujuliMurillo"><%= image_tag "googleb.png", :class => "icon" %></a>
			<a href="https://wordpress.com"><%= image_tag "mailb.png", :class => "icon" %></a>
		</div>
	</header>
<section>
	<div class="reg">

		<h1>Snippets.</h1>

		<p>Escribe una historia <br>o ayuda a continuar su historia a otro escritor</p>
	
		<%= link_to "Entra", stories_path, :class => "buttonhome" %>

	</div>
</section>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<head>
  <title>Snippets.</title>
  	<%= stylesheet_link_tag    'application', media: 'all' %>
  	<%= javascript_include_tag 'application' %>
  	<%= csrf_meta_tags %>
</head>

<%= yield %>

</html>

app/views/stories/_form.html.erb
<div class="forms">
	<% if is_root %>
		<%= form.label :title %>
		<%= form.text_field :title, class: "claseinput" %>
	<br>
	<% end %>
	<%= form.label :text %>
	<%= form.text_area :text, class: "claseinput2" %>
</div>
<div>
	<%= form.submit "Submit" %>
</div>

app/views/stories/create.html.erb
<h1>Stories#create</h1>
<p>Find me in app/views/stories/create.html.erb</p>

app/views/stories/delete.html.erb
<h1>Stories#delete</h1>
<p>Find me in app/views/stories/delete.html.erb</p>

app/views/stories/edit.html.erb
<body class="bgstory">

<nav class="nav">
	<ul>
		<li class="elemnav1">
			<h2>Snippets.</h2>
		</li>
		<% if user_signed_in? %>

		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "#{current_user.name}'s pad", user_path(current_user.id) %>
			<%= link_to "Sign out", destroy_user_session_path, class: 'salir', method: :delete %>
		</li>
		
		<% else %>
		
		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "Sign in", new_user_session_path, :class => "button" %>
			<%= link_to "Sign up", new_user_registration_path, :class => "button" %>
		</li>
		
		<% end %>

	
	</ul>	

</nav>

<section>

<div class="newstory">

	<h2>Edit your story</h2>
</div>

<div class="formstory">

<%= form_for @story do |f| %>
	<%= render partial: 'form', locals: {form: f, is_root: @story.root? } %>
<% end %>

</div>
</section>
</body>

app/views/stories/index.html.erb
<body class="background">

<nav class="nav">
	<ul>
		<li class="elemnav1">
			<h2>Snippets.</h2>
		</li>
		<% if user_signed_in? %>

		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "#{current_user.name}'s pad", user_path(current_user.id) %>
			<%= link_to "Sign out", destroy_user_session_path, class: 'salir', method: :delete %>
		</li>
		
		<% else %>
		
		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "Sign in", new_user_session_path, :class => "button" %>
			<%= link_to "Sign up", new_user_registration_path, :class => "button" %>
		</li>
		
		<% end %>

	
	</ul>	

</nav>

<section>

<div class="storiestitle">
	<p>¿A qué estás esperando? ¡Crea tu propia <%= link_to "historia", new_story_path %>! </p>
</div>

<% @stories.each do |story| %>
	<div class="storybox">
		<ul>
			<li><%= link_to "#{story.title}", story, class: "salir" %></li>
			<li><%= story.text %></li>
			<br>
			<li><%= link_to "Read more", story %></li>
		</ul>

	</div>
<% end %>

</section>

</body>

app/views/stories/new.html.erb
<body class="bgstory">

<nav class="nav">
	<ul>
		<li class="elemnav1">
			<h2>Snippets.</h2>
		</li>
		<% if user_signed_in? %>

		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "#{current_user.name}'s pad", user_path(current_user.id) %>
			<%= link_to "Sign out", destroy_user_session_path, class: 'salir', method: :delete %>
		</li>
		
		<% else %>
		
		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "Sign in", new_user_session_path, :class => "button" %>
			<%= link_to "Sign up", new_user_registration_path, :class => "button" %>
		</li>
		
		<% end %>

	
	</ul>	

</nav>

<section>

<div class="newstory">
	<h2>Your story</h2>
</div>


<div class="formstory">

<% if flash[:error] %>
	<%= flash[:error] %>
<% end %>

<%= form_for @story do |f| %>
	<%= render partial: 'form', locals: {form: f, is_root: true } %>
<% end %>

</div>
</section>
</body>

app/views/stories/show.html.erb
<body class="bgstory">

<nav class="nav">
	<ul>
		<li class="elemnav1">
			<h2>Snippets.</h2>
		</li>
		<% if user_signed_in? %>

		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "#{current_user.name}'s pad", user_path(current_user.id) %>
			<%= link_to "Sign out", destroy_user_session_path, class: 'salir', method: :delete %>
		</li>
		
		<% else %>
		
		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "Sign in", new_user_session_path, :class => "button" %>
			<%= link_to "Sign up", new_user_registration_path, :class => "button" %>
		</li>
		
		<% end %>

	
	</ul>	

</nav>

<section>

<div class="newstory">
	<h2>"<%= @story.title %>"</h2>
</div>
	
<div class="storyboxshow" id="contenedor">
	<ul>
		<li>
			<% @story.parents.each do |story| %>
				<%= story.title %>
				<br>
				<%= story.text %>
				<% end %>
		</li>
		<li>
			<%= @story.text %>
		</li>
	</ul>

	<div class="buttonstory" onclick="return show()">
	<a href="">Continuar historia</a>
	</div>

	<div class="newstory">
		<%= link_to "Edit", edit_story_path, class: "buttonsession" %> |
		<%= link_to "Stories", stories_path, class: "buttonsession" %>
	</div>
</div>



<div class="formstoryadd" id="addition" style="display:none;">
	<%= form_for @story.children.build, url: add_continuation_story_path(@story) do |f| %>
		<%= f.hidden_field :parent_id %>
		<%= render partial: 'form', locals: { form: f, is_root: false } %>
	<% end %>
</div>
<% if policy(@story).update? %>
  <%= link_to "Edit story", edit_story_path(@story) %>
<% end %>


</body>

app/views/stories/update.html.erb
<h1>Stories#update</h1>
<p>Find me in app/views/stories/update.html.erb</p>

app/views/users/show.html.erb
<body class="bgusers">

<nav class="nav">
	<ul>
		<li class="elemnav1">
			<h2>Snippets.</h2>
		</li>
		<% if user_signed_in? %>

		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "#{current_user.name}'s pad", user_path(current_user.id) %>
			<%= link_to "Sign out", destroy_user_session_path, class: 'salir', method: :delete %>
		</li>
		
		<% else %>
		
		<li class="elemnav2 buttonsession">
			<%= link_to "About Snippets", about_path %>
			<%= link_to "Sign in", new_user_session_path, :class => "button" %>
			<%= link_to "Sign up", new_user_registration_path, :class => "button" %>
		</li>
		
		<% end %>

	
	</ul>	

</nav>

<section>
	
<% if user_signed_in? %>

	<div class="newstory">
		<h3><%= current_user.name %>'s pad</h3>
	</div>
	
	<div class="myarea">
		<%= link_to (submit_tag "New Story"), new_story_path, :class => "story" %>
		<br>
		<div>
		<%= link_to "Home", home_path, class: "storylink" %>
		<%= link_to 'Logout', destroy_user_session_path, class: "storylink", method: 'DELETE' %>
		</div>
	</div>

<% else %>

	<h2>Nobody logued in</h2>

<% end %>

</section>
</body>